pipeline {
    agent any

    tools {
        maven "M3"
    }

    stages {
        stage('Gatling stress test go-calc') {
            steps {
                sh 'cd /gocalcstresstest && mvn clean gatling:test'
            }
        }
    }
}