pipeline {
    agent any
    stages {
        stage('Build Docker Image') {
            steps {
                sh "pwd && ls"
                sh "packer build /infra/packer-template.pkr.hcl"
            }
        }
    }
}