pipeline {
    agent any
    stages {
        stage('Build Docker Image') {
            steps {
                sh "go build -o go-calc/"
                sh "packer build infra/packer-template.pkr.hcl"
            }
        }
    }
}