pipeline {
    agent any
    stages {
        stage('Build go-calc') {
            steps {
                sh "cd go-calc"
                sh "go build"
            }
        }
        stage('Build Docker Image') {
            steps {
                sh "packer build infra/packer-template.pkr.hcl"
            }
        }
    }
}