pipeline {
    agent any
    environment {
            DOCKERHUB_LOGIN = credentials('dockerhub-login')
    }
    stages {
        stage('Build go-calc') {
            steps {
                sh "cd go-calc && go build"
            }
        }
        stage('Build Docker Image and publish on dockerhub') {
            steps {
                sh('packer build -var dockerhub_username=$DOCKERHUB_LOGIN_USR -var dockerhub_password=$DOCKERHUB_LOGIN_PSW infra/bake/packer-template.pkr.hcl')
            }
        }
    }
}